# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f6747d32c14daf8dd3168c7d45c343c96b77fe7eb0a45ca7dd2b516aecc7cf6d180bbcd0730ad1722578b6cf8079a5e780b7797bb4219c38f2c53a3fc934832

test:
  secret_key_base: 98e42f82cfa45a33ee1c124fae419564baebde46ab8bf781f3ead03f73ae6c47dcace47cd017e0660540b12624f4e36c882487bdf6dc9322a4c6f9f14b81a5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
